### ISSUE TITLE
BOT の必須機能は？

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/scripts#1]
「これが出来ないと始まらない」レベルの最低限の機能をリストアップします。

のちにバージョンアップするとして、今はなるべく削る方向でご意見ください。

- テキスト文字列をQiita記事に投稿（新規作成）できる
- テキスト文字列をQiita記事に上書き（更新）できる
- BOT自身の投稿記事を削除できる
- 投稿記事のステータスを変更できる（公開・限定公開など）

**Comment by KEINOS** [comment]
## 対Qiitaの必須機能
- [ ] Qiita記事の「作成とID取得」「更新」「削除」

## 対GitHubの必須機能
- [ ] GitHubからのWebHookによるトリガー起動
- [ ] BOTからのマージの実行

## 対Qiitadonの必須機能
- [ ] トゥートおよびトゥートIDの取得
- [ ] トゥートIDに対する返信
- [ ] 公開範囲を指定してトゥート or 返信
- [ ] フォロワーの情報取得
- [ ] フォロワーのQiitaでのユーザー名取得

## デプロイ先の必須機能
- [ ] `git clone`の実行によるアップデート（もしくはwgetなど）
- [ ] cronによるWebHook実行（５分間隔）

**Comment by hidao80** [comment]
対qiita の必須機能に「qiita記事の新着確認（スクレイピング？）」が足りない気がします。

あとはOK:thumbsup:です！

他に追加がなければ一旦クローズしていいと思います。

**Comment by KEINOS** [comment]
そうでした！対 Qiita に「新着Qiita記事の取得」を追加しました！

**Comment by KEINOS** [comment]
TL;DR に取りまとめました。

**Comment by hidao80** [comment]
👍

TODO が埋まっていくのがワクワクしますね！
