### ISSUE TITLE
プラグイン："Hello world!"をトゥート・削除するだけの機能

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/scripts#10]
# 'scripts'の"Hello world"から始めませんか

## 提案

そろそろ"scripts"リポジトリも動かし始めないと、なので。簡単なところからはじめませんか。（と、自分に言ってみる）

## 自分の案
以下の流れを考えています。
- [x] "just_to_say_hello_to_the_world-xxxxxxxx"でブランチを作成
- [x] "Hello World! "と返すだけのスクリプトからはじめてプルリク＆マージ
- [x] デプロイ先でCloneして動作確認
- [x] そのURLをBOTのトリガー（GitHubやCronのWebHook）先のURLと制定
- [x] ブランチを削除（自動デプロイは後日 別 issue ）

## 追加タスク
- [x] QithubのアカウントでQiitadonAPIのトークンを発行
- [x] 5分置きに未収載で"Hello world! ${YmdHi}"をトゥート
- [x] トゥート時、１つ古いトゥートを削除

## 補足
同時に、 #7 に準拠して基本ディレクトリも作成します。
----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（進捗 2017/10/05 現在）

- プラグインは「トゥートの内容だけを標準出力する機能」に限定（ #16 より）
- トゥートの実行はプラグインでなく、本体スクリプトから'system'ディレクトリ内のスクリプトが担当する
- 'plugin'および'system'の各スクリプトを呼び出すAPIの仕様は検討中（JSONベースの方向）

**Comment by hidao80** [comment]
質問が一つ。

「ブランチを削除」というのは次のうちどの解釈があっていますか？

A. ブランチを master に統合して、ブランチを削除
B. ブランチをプロトタイプとして完全に破棄

おまけ
Github の Markdown 的に、チェックボックスオンは、`- [x] ...`のようです。:sweat_smile:

**Comment by KEINOS** [comment]
> 「ブランチを削除」というのは次のうちどの解釈があっていますか？

 **A** の「ブランチを master に統合して、ブランチを削除」です。

本当は、"dev"ブランチを切って、BOTの稼働サーバーは"dev"ブランチをcloneするのが正攻法だと思うのですが、今は動いている感が欲しいのと、デプロイ先の挙動確認のため動く"master"が欲しいのです。

    チェックボックスオンは、`- [x] ...`のようです。😅

あ・・・何も出来ていないので、何もチェック入れなかったんです・・・すみません 😅 

- [x] 進捗なしです

**Comment by hidao80** [comment]
:thumbsup:

了解です！ まずは一言でいいので BOT から返事がもらえるとグッと来ますね！

**Comment by KEINOS** [comment]
あ！最初の投稿の下の`[*]`の部分を指していたんですね！

こりゃまた失敬！修正しました！

自分への戒めのために魚拓を取っておく
<img width="789" alt="2017-09-28 21 22 58" src="https://user-images.githubusercontent.com/11840938/30966410-c6cf6eb6-a493-11e7-8ace-b64579a55471.png">

**Comment by hidao80** [comment]
:thumbsup::smile:

**Comment by KEINOS** [comment]
プルリクのクローズで issue もクローズした！

と喜んでいたいのですが、そもそも最初の要件を満たさないでクローズしてました！

ので、再オープン！

`fixes #n`と`closed #n`の違いもあわせて確認して行きたい。

**Comment by hidao80** [comment]
👍

**Comment by KEINOS** [comment]
デプロイ先として下記で稼働できるようにしました。タスク（上記初回投稿の）チェック済み。

https://blog.keinos.com/qithub/

本当は `https://qithub.keinos.com/` にしたかったのですが、サーバーの有料SSLがこのサブドメインだけ無料SSL（Let's Enctypt）を許してくれず、時間がかかりすぎるので、とりあえず動くことを優先しました。（ボットからは見えないURLだし）

**Comment by hidao80** [comment]
:thumbsup:

おお〜、動作確認できました！ これで実装始められますね！

こうしちゃいられない、マイルストーンの立て方調べなくちゃ！:smiliy:

**Comment by KEINOS** [comment]
上記URLをCronが5分置きに叩くのを確認しました。

## 提案
引き続きトゥートの"Hello world!"をしてみたいと思います。
あわせて"_script"ディレクトリも作成してプルリクします。

## 自分の案
- [ ] QithubのアカウントでQiitadonAPIのトークンを発行
- [ ] 5分置きに未収載で"Hello world! ${YmdHi}"をトゥート
- [ ] トゥート時、１つ古いトゥートを削除

上記を網羅したら"Hello world!"を卒業し、クローズ。
返信トゥートは別 issue としたいと思います。

**Comment by hidao80** [comment]
:thumbsup:

そうですね。まずは定時トゥートができないことには始まりませんからね。

提案に全面賛成です。

マイルストーンは作りながら考えましょう！:smile:

**Comment by KEINOS** [comment]
> マイルストーンは作りながら考えましょう！:smile:

👍

**Comment by KEINOS** [comment]
"Hello world ${時刻}"トゥートのデプロイを手動で行いました。

### デプロイ手順（本稼働サーバを GitHub の master に追従する手順）

GitHub の'scripts'リポジトリを `clone`した、デプロイ先のディレクトリで以下を実行。

```
git pull origin
```
### 動作確認

- 手動更新： https://blog.keinos.com/qithub/index.php
- 確認先　： https://qiitadon.com/@qithub

<kbd><img width="490" alt="2017-10-02 23 58 02" src="https://user-images.githubusercontent.com/11840938/31083777-9342ebe4-a7cd-11e7-84f3-a5297a949dbf.png"></kbd>

`#qithub`のタグがある `#test` トゥートがデプロイ先（本番環境）からトゥートされたもので、cronによって5分おきに更新されます。（5分経過してからQiitadon画面を更新するとタイムスタンプが変わっていると思います）


`#qithub_dev`のタグがある `#test` トゥートは @KEINOS のテスト環境からのトゥートです。

**Comment by KEINOS** [comment]
## 問題点

前回トゥートを削除してからのトゥートなのでホームを汚さないとは言え、このままだとフォロワーのホームの上位に"Hello〜"が常に表示されることになります。

## 提案

"Hello world!" トゥートの最後の仕上げとして、URLに工夫をしてはどうでしょう。

例えば、この"Hello world"はプラグイン的に動作するようになっているので、**URLのクエリに指定があった場合のみ実行する**などです。
### 例
- "Hello world!"プラグインが実行されるURL（他の定例処理は行わずピンポイント実行）
```
https://blog.keinos.com/qithub/index.php?issue=10
```
- "Hello world!"プラグインが実行されないURL（通常の定例処理用）
```
https://blog.keinos.com/qithub/index.php
```

**Comment by hidao80** [comment]
👍 

GET なら cron から制御できるので、今後 cron を増やして定例処理を増やすこともできそうですね！

**Comment by KEINOS** [comment]
そうかGitHubからのWebHookも

```
https://blog.keinos.com/qithub/index.php?issue=github
```
とすれば、処理しやすいですね。うんうん。

**Comment by KEINOS** [comment]
プラグインの issue である旨がわかりやすいように issue のタイトルを修正しました。

検索をした時にタイトルを見てピンと来ますかね？

**Comment by hidao80** [comment]
👍

**Comment by KEINOS** [comment]
TL;DRを追加〜

**Comment by hidao80** [comment]
PR #21 のマージに伴い、本 issue も解決とします。

お疲れさまでした！👍😄
