### ISSUE TITLE
'scripts'リポジトリの説明文の変更

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/scripts#12]
## 提案・相談・質問内容

["scripts"リポジトリの説明文](https://github.com/Qithub-BOT)が下記の通り古いので変更をした方がいいと思います。

    QittadonのBOT「BOTch」用のロジック置き場

## 自分の案

    QiitaとQiitadonのユーザ・コラボレーションをサポートするBOT「Qithub」の本体スクリプト制作をコラボするためのリポジトリ

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by KEINOS** [comment]
改めると、むしろ上記のリポジトリ説明文は、もう少し短くして、リポジトリ内の"README.md"の方を充実させた方が良い気もしてきました。

    QiitaとQiitadonのコラボ用BOT「Qithub」の本体スクリプト・リポジトリ

**Comment by hidao80** [comment]
:thumbsup:

わかりやすく簡潔で、とても良いと思います！

**Comment by KEINOS** [comment]
'Scripts'リポジトリの説明文を更新しました。'Items' repo の説明と語感をあわせるために、文末に「実際のコラボ・アプリ置き場。」も独断で追加してしまいましたので判断お願いします。
https://github.com/Qithub-BOT/

ちょっと余計かな → 💩 
いいんじゃない → 👍

**Comment by hidao80** [comment]
:thumbsup:

**Comment by KEINOS** [comment]
👍
