### ISSUE TITLE
'scripts' のプログラミング・チーム作成

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/scripts#13]
## 提案

[Qithubの基本仕様](https://github.com/Qithub-BOT/items/blob/c3b28c55eb38d17125c7b029ef1177bcc2e9443b/1a52282f0b132347c2b1.md#qithub-の仕様)の[基本ルール](https://github.com/Qithub-BOT/items/blob/c3b28c55eb38d17125c7b029ef1177bcc2e9443b/1a52282f0b132347c2b1.md#基本ルール)に伴い、ラベリングチーム同様、プログラミングチームも作成した方がいいと思います。

`items`の issue かとも思ったのですが、こちらの方が適切かと思いました。

## 自分の案

「ラベリングチーム」でなく「ラベルチーム」であるため、「プログラミングチーム」も「プログラムチーム」が良いと思います。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by hidao80** [comment]
「プログラムチーム」立ち上げ、賛成です。名称もこれでよいと思います。

が、チームに付与される権限がいまいちイメージできていません。

「プログラムチーム」に所属してる（⊃Organzation メンバーである）プログラマに**のみ与えられているもの**（リソース、権限）ってなんでしょうか？ \
「プログラムチーム」にのみマージ権限が与えられるイメージ？

何か特権がないと、チームにする必要性を感じなくて。

**Comment by hidao80** [comment]
👍 \
自分が書いた内容を忘れかけていました。（汗

名称も「プログラムチームで」 👌  です！

**Comment by KEINOS** [comment]
プログラムチームを以下の通り作成しました。
<img width="998" alt="2017-10-01 11 01 55" src="https://user-images.githubusercontent.com/11840938/31051007-02e41ce8-a698-11e7-86b2-e7947d40dea7.png">

現在のチームのメンテナは以下の通りです。

| チーム名 | メンテナ | チームの主な担当 | 参考 issue |
| --- | --- | --- | --- |
| ラベル | @hidao80 | issueにラベル（緊急度、カテゴリ）を割り当てる担当チーム | ラベリングの種類 Qithub-BOT/items#5 <br>ラベル「緊急度：x」の指針を決めましょう Qithub-BOT/items#6 |
| プログラム | @KEINOS | issue に割り当てられた担当者以外のプルリクをマージする担当チーム。（ 自身のプルリクを除く） | BOT開発におけるマージの基準とデプロイ Qithub-BOT/scripts#5 |

## 参考文献
Qithub 設定資料集
https://github.com/Qithub-BOT/items/blob/master/1a52282f0b132347c2b1.md

**Comment by hidao80** [comment]
👍
