### ISSUE TITLE
BOT による新規Qiita記事の作成とリポジトリ同期

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/scripts#3]
GitHubに置かれたMarkdownをQiita記事に流し込む際の問題となるのがQiitaの記事IDとの紐付けです。

理想で言えば、

1. コラボレーターがローカルに新規作成した記事をプルリクしてマージされるとQiitaに新規投稿される

1. 以降は通常のコラボ（修正→プルリク→マージ→更新のループ）となる

ですが、この時に２つのトラブル要因が発生します。

- リポジトリにあるファイル名とQiita記事IDの紐付け
- ファイル名の重複やファイル名の変更

そこで、コラボ用の新規記事を作りたい場合、「BOTが作成したブランク記事に対してのみと制限する」としてはどうでしょう。

具体的には以下の動作を考えています。

**TL;DR**「トゥートによる新規作成リクエストで作成された記事のみがコラボ（更新）対象となる」

## 新規Qiita記事作成までのフロー

1. ユーザAがQiitadonからBOTにメンション（ダイレクト？）トゥート
2. ユーザAのQiitaアカウントIDを取得（＠ユーザA）
3. トゥート内容に問題がなければBOTがQiitaに**限定公開**で「 ＠ユーザA が新規コラボ記事をリクエストしました。${トゥート内容}」といった記事を新規作成しQiita記事IDを取得
4. `items`リポジトリに同内容のMDファイルを作成
5. 記事を作成した旨をユーザAのトゥートに返信
6. ユーザAはリポジトリをローカルにクローンして以下Gitの通常フロー

「記事の更新」や「限定公開→公開」のステータス変更は別 issue にしたいと思います。

**Comment by hidao80** [comment]
プルリク→マージ→公開 のフロー、賛成です。

### ID 振り出しの件

記事作成フローの Qiita 記事 ID 振り出しを BOT・Qiita API 間の「全自動」かつ「本家に問い合わせ」をしているところが確実で良いと思います。
名前衝突の可能性を限りなくゼロにできていると考えます。

# 記事作成までのフローの件

コラボレーターから BOT への問い合わせトゥートはダイレクトではなく、メンションを推します。理由は他のコラボレーターから確認することができるからです。

本 BOT を使うからには記事 ID を非公開にする理由はなく、トラブル（不具合など）が発生したときに本人以外にも追跡できるようにするためです。

**Comment by KEINOS** [comment]
> BOT への問い合わせ**トゥートはダイレクトではなく、メンション**を推します

👍 

では以下の仕様でOKクローズでしょうか。

## Qiitaコラボ記事の新規作成

- Qiita の Qithub アカウントで新規記事を作成、記事IDを取得する
- 同記事IDで`items`repo（master）にテキストファイルを作成する
- これらの動作はBOTが行うこととする（それまでは手動。2017/09/27 現在 @KEINOS が担当）

## `issue`リポジトリの同期

- `items` repoにおけるファイル名は Qiita記事のIDと同じとする（README.mdのみ例外）
- 拡張子は".md"とする（＜Qiita記事ID＞.md）
- `items` repoにはQiita側の Qithub のアカウントに存在しない記事は置いてはいけない（README除く）

## BOTの動作

1. ユーザA が Qiitadon から BOT に**メンション**・トゥート
2. ユーザA の Qiita アカウントID を取得（＠ユーザA）
3. トゥート内容に問題がなければ BOT が Qiita に**限定公開**で記事を新規作成
4. Qiita記事IDを取得
5. `items`リポジトリに同内容のMarkdownファイルを作成
6. 記事を作成した旨を ユーザA のトゥートに返信
7. ユーザA は`items`リポジトリをローカルにクローンして以下Gitの通常フロー

**Comment by hidao80** [comment]
:thumbsup:

**Comment by KEINOS** [comment]
# BOT による新規Qiita記事の作成と同期の仕様

## Qiitaコラボ記事の新規作成

- Qiita の Qithub アカウントで新規記事を作成、記事IDを取得する
- 同記事IDで`items`repo（master）にテキストファイルを作成する
- これらの動作はBOTが行うこととする（それまでは手動。2017/09/27 現在 @KEINOS が担当）

## `issue`リポジトリの同期

- `items` repoにおけるファイル名は Qiita記事のIDと同じとする（README.mdのみ例外）
- 拡張子は".md"とする（＜Qiita記事ID＞.md）
- `items` repoにはQiita側の Qithub のアカウントに存在しない記事は置いてはいけない（README除く）

## BOTの動作

1. ユーザA が Qiitadon から BOT に**メンション**・トゥート
2. ユーザA の Qiita アカウントID を取得（＠ユーザA）
3. トゥート内容に問題がなければ BOT が Qiita に**限定公開**で記事を新規作成
4. Qiita記事IDを取得
5. `items`リポジトリに同内容のMarkdownファイルを作成
6. 記事を作成した旨を ユーザA のトゥートに返信
7. ユーザA は`items`リポジトリをローカルにクローンし以降はGitの通常フロー
