### ISSUE TITLE
プラグイン："roll-dice" で emoji を返せないか（オプション）

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/scripts#41]
## 提案

PR #38（関連 #39 #40 ）の「Dice Roll」プラグインですが、トゥート用にオプションで絵文字で返せるようにしてはどうでしょう？

#### API リクエストパラメーター
```
[
    'is_mode_debug" => 0,
    'dicecode' => '3d11',
    'use_emoji' => 'yes',
]
```
#### API レスポンス
```
[
    'result' => 'OK',
    'value' => [
        'role' => [ ':zero:', ':four:', ':one::one:' ],
        'sum' => 15,
    ],
]
````

## TL;DR（進捗 2017/11/05 現在）

- 審議中 ( ´・ω) (´・ω・) (・ω・｀) (ω・｀ )

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by hidao80** [comment]
👍いいですね！😁

実装もそれほど複雑ではない気がします（直感で、ですが）。

**Comment by hidao80** [comment]
#47 マージしましたので、クローズします。

**Comment by KEINOS** [comment]
デプロイしました。

クエリによるリクエストのパラメーターは TL;DR に記載。以下動作サンプルです。
2017/11/10 の時点でプラグインの規制緩和に対応していません。

## クエリのリクエスト例

### 通常リクエスト
https://blog.keinos.com/qithub/?process=roll-dice&dice_code=2d3

### emojiリクエスト（ダイスコード：デフォルト）
https://blog.keinos.com/qithub/?process=roll-dice&use_emoji=yes

### emojiリクエスト(デバッグ）
https://blog.keinos.com/qithub/?process=roll-dice&use_emoji=yes&dice_code=2d3

**Comment by hidao80** [comment]
👍👏😄
