### ISSUE TITLE
プラグイン："dice-roll" が命名規則と異なる（名前およびディレクトリ名）

### ISSUE THREAD

**Issue by hidao80** [Qithub-BOT/scripts#43]
## 提案内容

今気がつきましたがこのプライグイン名、プラグインの命名規則的には `<DO>-<WHAT>` なので、「roll-dice」が筋でしたね。😓

## 自分の案

今更ですが、ディレクトリ名および index.php 内のエントリポイントを `roll-dice` にしませんか？

`roll-dice` で👌なら😎🙏。

## TL;DR（進捗・結論 2017/11/06 現在）

- PR #45 で対応中

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by KEINOS** [comment]
> プラグインの命名規則的には `<DO>-<WHAT>`

確かに。気づきませんでした！ 

👌 → 😎 👍 

issue #44 のバグ（挙動の不具合）とあわせて PR #45 で対応しまーす。
