### ISSUE TITLE
プロセス：「新着Qiita記事トゥート」の親トゥートの CW がおかしい

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/scripts#44]
## バグ報告

cron実行されるデプロイ先から新着Qiita記事トゥート（「#qithub_dev」タグのないトゥート）のうち、トゥートを始める旨の初回アナウンスで「CW」が有効になっていません。

https://qiitadon.com/@qithub/98952177536428625

## 自分の案

https://blog.keinos.com/qithub/index.php?process=toot-daily-qiita-items

上記、新着Qiita記事トゥートのトリガーの直リンを叩くと、未投稿トゥートがある場合エラーもでます。
エラーは「テスト」タグの付いた記事は無視する処理が抜けているっぽい内容なので、デプロイ先で抜けているコミットがあるようです。（要確認です）

以下のコマンドをデプロイ先のディレクトリで実行し、リモートの`master`を「完全上書き」しているハズなのですが、、、もっと確実な上書きコマンドってありますかね？

```
$ git fetch origin
$ git reset --hard origin/master
```

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（進捗・結論 2017/11/05 現在）

- 審議中 ( ´・ω) (´・ω・) (・ω・｀) (ω・｀ )

**Comment by hidao80** [comment]
嫌な予感がします。🤔

origin の参照先 URL は本当に https://github.com/Qithub-BOT/scripts.git ですか？

**ローカルから Push して、origin === ローカルリポジトリ ということはない**ですよね？

**Comment by KEINOS** [comment]
> origin の参照先 URL は本当に https://github.com/Qithub-BOT/scripts.git ですか？

以下のように確認してみたのですが、合っているっぽいんですよね。

```
-bash-4.2$ git remote -v
origin  https://github.com/Qithub-BOT/scripts.git (fetch)
origin  https://github.com/Qithub-BOT/scripts.git (push)
```

あ、DEV側のファイルでリモートの master にコミットされていないものが、あるの、か？

**Comment by hidao80** [comment]
>あ、DEV側のファイルでリモートの master にコミットされていないものが、あるの、か？

次はその線が怪しいですね。

っていうか、`$ git pull` では上手くいかない？ pull が本筋だと思ってました。

**Comment by hidao80** [comment]
フラッシュアイデアですか、**ローカルのブランチが master でない**可能性はないですか？

**Comment by KEINOS** [comment]
> っていうか、`$ git pull` では上手くいかない？ 

`pull`だと差分変更だけを引っ張ってくるので、（通常はありえませんが）デプロイ側で変更・コミットがあった場合はそれが残ってしまうため、**新規で`clone`した状態**、つまりリモート master とまったく同じ内容にしたいので `--hard`に`reset`しているのですが・・・

と、考えるとやはり**DEV環境にはあって、どこにもコミットされていないファイルがある**可能性が大ですね。チェックしてみます。

**Comment by KEINOS** [comment]
今晩中にやっつけたいので 明日まで 😎 で進めていいですか？

**Comment by KEINOS** [comment]
[#43](https://github.com/Qithub-BOT/scripts/issues/43#issue-271280199) の「 😎 🙏 」と合わせて対応することに 😎

**Comment by hidao80** [comment]
👍👌😎🙏

**Comment by KEINOS** [comment]
あれ？ちゃんと動いている・・・
https://qiitadon.com/@qithub/98956424559491669
なんぞ？原因がわからんのはコミットちゃん #明日まで様子見

**Comment by KEINOS** [comment]
PR #47 のDEV環境で正常動作確認。マージ後、修復されている（はず）

**Comment by hidao80** [comment]
👍

**Comment by KEINOS** [comment]
デプロイ（本稼働）先で動作確認できたので close し 💪 

https://qiitadon.com/@qithub/98980819319668918

**Comment by hidao80** [comment]
👍👏😄
