### ISSUE TITLE
プロセス：「新着Qiita記事トゥート」で親トゥートが抜けることがある

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/scripts#46]
### 「新着Qiita記事」で定時のトゥート開始を宣言するトゥートが抜け落ちる

現在5分おきに cron でトゥートされる「新着Qiita記事」で、定時（現在１時間置き）の区切りにトゥートを開始する旨を宣言するトゥート（スレッドの親トゥート）が発信されないことがある。

<kbd><img width="993" alt="2017-11-09 22 16 37" src="https://user-images.githubusercontent.com/11840938/32607615-f586c644-c59c-11e7-8fca-31094d73d104.png"></kbd>

## 自分の案

おそらく、以下の2点が発生している可能性があります。

1. 親トゥート発信時に Qiitadon 側で 50x 系のエラーが発生している
2. BOT の稼働している激安サーバー自身が重いことがあるので、処理落ちしている

「200」 （正常処理）を検知するまで、つまり宣言トゥートが**正常にトゥートできるまで以降のトゥートはペンディングにする**などの対策をすべき。

（記事のトゥート自体は抜けがあっても良いと思うが、宣言トゥートは確実性が必要と思われる）

## TL;DR（進捗・結論 2017/11/10 現在）

- 対応中 (｡´･ω･)｡ﾟｶﾁｬｶﾁｬ

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by hidao80** [comment]
👍😎🙏

**Comment by KEINOS** [comment]
新着Qiita記事のスレッドで親トゥートが抜ける問題、 PR #59 で修正しました！

**Comment by KEINOS** [comment]
あわせて、本番にもデプロイしました！

**Comment by hidao80** [comment]
👍😄👏
