### ISSUE TITLE
BOT開発におけるマージの基準とデプロイ

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/scripts#5]
#4 より、`script`リポジトリにおける**マージ基準を決めたい**のですが、以下はいかがでしょう。

## 基本基準
- BOT開発のプルリクは自動化しない
- プルリクのマージは issue に割り当てられた担当者が行う（割り当て方法は要検討）
- コードレビューは基本的にしない。マージ後の不具合が多いようであれば別途検討する

## デプロイに関して
- BOTの稼働先は当面 @KEINOS の個人サーバーで行う
- マージされたものは自動的に上記サーバーに反映（デプロイ）されるようにする

**Comment by hidao80** [comment]
:thumbsup:

シンプルかつ必要なものが全て含まれたいると思います！

**Comment by KEINOS** [comment]
👌

**Comment by hidao80** [comment]
クローズされた issue に投げてごめんなさい。

issue の登録されていないプルリク（プロジェクト外部からの参加者からのプルリク）のマージ決済はだれが行いますか？

ドキュメントには

- プルリクのマージは **issue に割り当てられた担当者**または**プログラミングチームのメンバー**が行う（割り当て方法は要検討）

と記述しようと考えています。

OK / NG / 対案お願いします。

**Comment by KEINOS** [comment]
👌 👍

**Comment by KEINOS** [comment]
👏 ✌️ 👌 👁

**Comment by hidao80** [comment]
…歳がばれる！（ささやき声で）
