### ISSUE TITLE
プロセス：「新着Qiita記事」トゥートにReTootリンクを埋める

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/scripts#52]
## 提案
「新着Qiita記事」のトゥートに該当記事へのリンクだけでなく、トゥートするリンクも併せて記載してはどうか。

## 状況説明

現在「新着Qiita記事」は非公開トゥート（※１）および未収載トゥート（※２）でトゥートされます。

未実装ですが、今後は特定数の「ブースト」や「お気に入り」が付いた場合には「ブースト」もしくは「改めて公開でトゥート」する仕様になります。

※１）現在は非Qiitadonユーザーの記事。今後はフォロワー。
※２）現在はQiitadonユーザーの記事。今後はフォロワー。

LTLも汚さないのでこの仕様は悪くないと思うのですが、現在「あ、この記事いい」と思っても前者の **「非公開トゥート」の場合はブーストできず「お気に入り」のみ** です。（まぁ当然ですが）

## 自分の案

<kbd><img width="296" alt="2017-11-11 14 12 44" src="https://user-images.githubusercontent.com/11840938/32686610-76b6389a-c6eb-11e7-8e4d-daf08f4b531a.png"></kbd>

さて、上記図のように Qiita に「Toot」リンクが設置されてて気づいたのですが、「`https://qiitadon.com/share?text=URLエンコード・テキスト`」のリンクでトゥート内容を指定できるので、**非公開トゥートは以下のフォーマットにしてはどうでしょう**？

```
【新着Qiita記事】

『<タイトル>』 @<ユーザー>
http://qiita.com/<ユーザー>/items/<記事ID>

[#<タグ1> #<タグ2> #<タグn>]
ReToot! → https://qiitadon.com/share?text=${URL}
```

### `$URL`の内容

- 上記トゥートと同内容（ReTootリンクなし） ＋ "#boostoot of ＠qithub" へのメンション付き

### 期待する効果

- ＠Qithub の認知度向上

### 懸念する事項

- 500文字制限
- 本家 Toot ボタンとモロかぶりする

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（進捗 2017/11/11 現在）

- 審議中 ( ´・ω) (´・ω・) (・ω・｀) (ω・｀ )

**Comment by hidao80** [comment]
> 上記トゥートと同内容（ReTootリンクなし） ＋ "#boostoot of ＠qithub" へのメンション付き

「boostoot」って語呂が良くて👍

```
【新着Qiita記事】

『<タイトル>』 @<ユーザー>
http://qiita.com/<ユーザー>/items/<記事ID>

[#<タグ1> #<タグ2> #<タグn>]
Boostoot! → https://qiitadon.com/share?text=${URL}
^^^^^^^^^^
```

がイイ！

### 500 文字超えた場合

text の先頭に `#boostoot of @qithub\n` 、末尾に `…` として、 文字を超える部分は切り落とすことを提案します。

#### 例）

```
#boostoot  of @qithub
@hidao ありがとうございます。
そういうことだっんですね。
（中略）
やっぱり青汁…
```

### 本家 Toot ボタンとモロかぶり問題

qiitadon 側にかぶる機能が**いまのところ**ないので、qiitadon 側のインタフェースとしては意義があると思います。

それを言ったら Qithub の存在意義が危ぶまれますが、 Qithub-BOT/items#14 により存在意義が多様化しているので、純粋な BOT としてまだまだ活躍の場は残されていると思います。
