### ISSUE TITLE
プロセス：「新着Qiita記事」でQiita記事がスパムの場合の対処

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/scripts#56]
## 相談

「新着Qiita記事」のトゥートでたまにスパム記事が入ります。

## 自分の案

現状は**そのまま**がいいかと。「機械学習でスパム記事か判断する」プラグインとか面白そうとは思うのですが、サーバーが・・・。

Qiitadonユーザーにまでなってスパムを投稿している業者が**まだ**出ておらず、「未収載」トゥートにはならないため**被害を受けるのはフォロワーだけ**であり周りには迷惑はかけないからです。（フォロワー涙目）

むしろ、Qiita記事を開いてスパムと気づいたらスパム報告してもらう旨を初回トゥートに含めるとか。（すでに長いので冗長になるかしら）

<kbd><img width="892" alt="2017-11-13 14 03 06" src="https://user-images.githubusercontent.com/11840938/32710705-b57c1f84-c87d-11e7-88c6-87fc554b7929.png"></kbd>

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（進捗 2017/11/13 現在）

> 特に対策しません。

### 理由

**新着記事の通知が本筋であって、Qiita 記事のクオリティに言及するものではない**からです。

**Comment by hidao80** [comment]
そのままに👍

Qithub は**新着記事の通知が本筋であって、Qiita 記事のクオリティに言及するものではない**と考えます。

スパマーとのいたちごっこは Qiita の責任範囲であって、Qithub は**投稿された事実のみをレポートするのが筋**だと思います。

P.S.  
人工知能使うったって、「スパム記事かくあるべし」みたいなものがないとスパム認定できないと思うのですが。大量のスパム記事を読み込ませて学習する？😓

P.P.S.  
Qiita にポストした段階で、公開前にスパムフィルターにかけてもらえるといいですね。

**Comment by KEINOS** [comment]
👌 では基本**放置**ということで 👍 

> 「スパム記事かくあるべし」みたいなものがないとスパム認定できない

スパム記事を用意するのも大変ですしね。新着トゥートに返信でスパムを報告してもらって記事を学習させる、とかも考えたのですが、それだったら Qiita記事 から報告してもらえばいいや、と。 😄 

> Qiita にポストした段階で、公開前にスパムフィルターにかけてもらえるといいですね。

一応、フィルターもかけているそうです。最近英語の記事も増えているらしく、判断が難しくなってきているそうです。まさに「スパマーとのいたちごっこ」ですな。

👉 TL;DR 済
