### ISSUE TITLE
BOT開発における主な開発の流れ

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/scripts#6]
ばんばんコードを書いてプルリクも良いのですが、KISSが夢で終わらないように、以下のような流れにしたいのですがいかがでしょう？

1. 実装予定／希望の機能と仕様を**トゥートできる程度の量**で issue を立てる
2. 👍 が付いたら実装担当者を割り当てる
3. コーディングをする
4. 悩んだら 1 の issue でヘルプを求める（3に戻る）
5. プルリク＆マージを実行する（同時にデプロイされる）
6. `items`の仕様ドキュメントに実装した機能と仕様をコピペする（以降は`items`のフローに準拠）

※ 実装した旨をBOTのフォロワーに通知すべきかは別途検討します。

**Comment by hidao80** [comment]
すべての変更にissueを立ててると、参入障壁が高すぎると思います。（注:我々は issue を立てることを対する抵抗感がマヒしつつあります！ 他人のリポジトリに issue を立てるときの気持ちを思い出しましょう！）

ので、対案は

1. コーディングする
3. 悩んだら issue でヘルプを求める
2. プルリクする
4. ふさわしくない（コミットがでかすぎる、Organizaion の目的とかけ離れた機能をじっそうしている）

**Comment by hidao80** [comment]
スイマセン、間違えてクローズしました。

再オープンします。

**Comment by KEINOS** [comment]
> 参入障壁が高すぎる

確かに麻痺してますね！issue の潰し込みもプチプチじゃないんだから。

「**自由にコーディングしてアップ（プルリク）してみる**」くらいの気軽さでいいかもしれませんね。:thumbsup:

では、当リポジトリは以下の開発の流れで進めることとします。

## BOT開発における主な開発の流れ
1. コーディングする
2. 悩んだら issue or qiitadon でヘルプを求める
3. プルリクする
4. ふさわしくないときは、**理由をコメントに書き、プルリクを棄却する**
    - コミットがでかすぎる
    - Organizaion の目的とかけ離れた機能を実装している
    - etc.
5. マージを実行する（同時にデプロイされる）
6. `items` の仕様ドキュメントに実装した機能と仕様を記入する（以降はitemsのフローに準拠）
