### ISSUE TITLE
プロセス：「新着Qiita記事」の「取りまとめ」が抜けることがある

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/scripts#62]
## 報告

定時処理の新着Qiita記事の 取りまとめ トゥートが抜けることがあります。

抜ける例： https://qiitadon.com/@qithub/99025551775287913

## 自分の案

タグが多すぎて500文字制限を超えているのが原因なので、２回にわけてはどうか

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（結論 2017/12/12 現在）

- タイムラインを汚さず、かつハッシュタグ検索にもヒットさせる重要なポイントであるため、**複数回にわけて全タグをトゥートする**ようにする
- <del>[ページカウント（n/m）の表記ぶんの文字数が500文字のカウント対象になっていないため、たまに抜ける問題](#issuecomment-348092438)</del> PR #76 で対応済み

**Comment by hidao80** [comment]
正しく表示されているように見えますが…？

もしかして https://qiitadon.com/@qithub/99025551623771444 のこと？

タグ一覧の途中でトゥートが切れてますね。ちょっくらソースを眺めてみます。

**Comment by hidao80** [comment]
あれ、上記私のコメントのトゥートを再表示したらちゃんと表示されました。

でも、「取りまとめトゥート」が何を指しているのかわかりません。

抜ける例には抜けているので表示されてないし、@qithub のタイムラインを見ても何が足りないのか分からないや。

**Comment by hidao80** [comment]
ジャストアイデアですが、Qiita のタグは自由度が高いので、この先も Qithub のトゥートにものすごく長いタグが複数入る可能性があります。

トゥートを複数に分けるのもいいですが、**頻出タグ TOP 10 とするのはどうでしょうか？**

網羅できないので Qithub との趣旨と異なるかもしれません。悩みどころです。🤔

**Comment by KEINOS** [comment]
言葉足らずですみません！ 💦 そうです「取りまとめ」トゥートとはスレッドの最後にトゥートされる「`タグの一覧が表示されるトゥートのこと`」のことで「 :memo: 【 x時のQiitaのタグ一覧】[もっと見る]」とトゥートされたものです。

<kbd><img width="697" alt="2017-11-19 14 59 08" src="https://user-images.githubusercontent.com/11840938/32987873-781d925a-cd3a-11e7-850e-e79ce4611af9.png"></kbd>

#### 抜けてるスレッド
https://qiitadon.com/@qithub/99025551775287913

#### 抜けめのないスレッド
https://qiitadon.com/@qithub/99025551623771444

### 「取りまとめ」トゥートの重要性

念のため（私自身）の整理も含めて説明すると、この「取りまとめ」トゥートを「**公開**」でトゥートすることで、ハッシュタグ検索時にスレ全体をヒットさせる役割があります。

というのも、新着Qiita記事の各々のトゥートは「未収載」or「非公開」であるため、**個々の記事はハッシュタグ検索には表示されない**からです。

検索のヒット自体は「取りまとめ」トゥートですが、クリックしてスレを開くと「未収載」トゥートを、BOTのフォロワーは「非公開」トゥートも見れるようになります。

これにより、タイムラインを汚さず、かつハッシュタグ検索にもヒットさせる重要なポイントなので、やはり**若干手間でも複数回（おそらく２回程度）にわけるようにするのが良い**と思うのですが、いかがでございましょ。

**Comment by hidao80** [comment]
複数回に分けて全タグトゥートに👍

TL;DR  
> タイムラインを汚さず、かつハッシュタグ検索にもヒットさせる重要なポイントなので、やはり**若干手間でも複数回（おそらく２回程度）にわけるようにするのが良い**と思う

なるほど！ その効果、私はすっかり失念していました。

**Qiitadon のタグ検索にかける**のなら、全タグ必須ですね。

**Comment by KEINOS** [comment]
👍 

では、プラグインの規制緩和 issue #42 の後、公開ステータス変更 issue #61 の前に PR して close する方向で！

👉 TL;DR 済

**Comment by hidao80** [comment]
👍👌🙏💪

…日本語を emoji にコンパイルしている自分に気づく。

**Comment by KEINOS** [comment]
PR #68 で fix しましたー

**Comment by KEINOS** [comment]
https://qiitadon.com/@KEINOS_BOT/99069434654350928
DEV環境では分割されている（金曜でないと投稿が少ないので、上記テストでは300文字に制限）

**Comment by KEINOS** [comment]
### 報告
500文字を超えた場合の分割トゥートはされるようになったのですが、たまに初回の方のトゥートが抜けます。
https://qiitadon.com/@qithub/99091612068581075

#### 原因

カウントしたら502文字だったので、おそらく[分割時にCWに追加されるテキスト「[n/m]」のぶん](https://github.com/Qithub-BOT/scripts/blob/master/includes/proc/toot-daily-qiita-items.php.inc#L184)が[カウントされていない](https://github.com/Qithub-BOT/scripts/blob/master/includes/proc/toot-daily-qiita-items.php.inc#L137-L140)のだと思います。

#### 対策案

[タグの前後の改行ぶん追加のカウントをしているあたり](https://github.com/Qithub-BOT/scripts/blob/master/includes/proc/toot-daily-qiita-items.php.inc#L127)に、`[nn/mm]`（７文字）ぶんを追加してはどうか。

**Comment by hidao80** [comment]
👍😄

😎🙏

**Comment by KEINOS** [comment]
本件、対応中です。ローカルの Git の調子が悪いので、fix 次第修正して PR いたし 💪 
年末でいささかペース落ち気味ですが、気長にお待ちください。

**Comment by hidao80** [comment]
「俺、正月休みになったら PR するんだ…」はフラグ過ぎ。😁

ベータリリースはできているので、年末進行を優先で、のんびり進めていきましょう！

ご多忙だと思いますので、くれぐれもご自愛ください😊
