### ISSUE TITLE
プロセス：「新着Qiita記事」でタイトル「テスト」を排除

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/scripts#65]
## 提案

タイトルが「テスト」もしくは「test」だけの記事は 新着Qiita記事 から除外したい。

## 自分の案

現時点で Qiita 記事のタグに[「テスト」「test」が含まれるとトゥートから除外されるようになっています](https://github.com/Qithub-BOT/scripts/blob/master/includes/proc/toot-daily-qiita-items.php.inc#L255)。そこで、タイトルも同じ条件で検知対象にしてはどうか。

除外記事の例： https://qiita.com/tmp_llc/items/027e709366c59cc11e85

## 補足

プライオリティは低めですが、忘れそうなので。備忘録として。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（結論 2017/11/20 現在）

- 以下の条件にマッチした記事は除外
```
       ('TEST' == strtoupper(trim($title)))
    or ('テスト' == trim($title))
    or ('てすと' == trim($title))
```
- PR 待ち

**Comment by hidao80** [comment]
タイトルに「テスト」、「test」が**含まれる**という条件なら**反対です**。

以下のような知見が発見できなくなるためです。

- モンキーテスト耐性を上げる記事
- ペネトレーション（システム侵入）テストに関する記事
- 単体/結合テストに関する記事
- etc.

## 対案1

以下の条件のどちらかが満足する場合、その記事をトゥート対象から除外する。

- タイトルが「trim('テスト')」「trim('てすと')」に一致する
- タイトルが `'TEST' == strtoupper($title)'` を満足する

**Comment by KEINOS** [comment]
言葉足らずでした！対案１がより具体的に意図した内容です！

テストのみのスタンドアローンコンプレックスな記事が対象です。

**Comment by hidao80** [comment]
👍

**Comment by KEINOS** [comment]
PR #68 で新着Qiita記事のタイトルが「テスト」のみの場合はトゥートをスキップ（無視）するようにしました。コミットに fix #65 を入れ忘れたので自動クローズされないかも。
