### ISSUE TITLE
プロセス：「新着Qiita記事」の取りまとめトゥートで空白タグが入る

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/scripts#69]
## 報告

取りまとめトゥートで「#」だけの（空白の）タグが入る
https://qiitadon.com/@qithub/99086893303555603

## 自分の案

Qiita, Qithub ともに**空白タグの処理をしていないのが原因**です。

Qiita記事側のタグ入力時に、挿入補助（補完）機能により「# #MyTag #」といった空のタグが入ることがあり、Qiita API自体も空のタグとして返してくるのが原因です。

特に、機能として支障はありませんが、やはり見っとも無いので[タグ一覧を抽出するとき](https://github.com/Qithub-BOT/scripts/blob/master/includes/proc/toot-daily-qiita-items.php.inc#L133)に、以下のような空白タグをスキップする処理を入れるといいか、と。

```
$tag = trim( $tag );
if ( Empty( $tag ) ){
    continue;
}
```

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（結論 2017/12/12 現在）

- 見えないものは、見えない方が精神衛生上いいので対処することに → PR #76 で対応済み

**Comment by hidao80** [comment]
👍

**Comment by KEINOS** [comment]
> 最初の職場で「バグじゃない！ 不具合と呼べ！」と刷り込まれたので、
> バグという言葉に過敏です。😅

確かに、動いてはいるのでバグではないですな。 😄 

内容も、歩いてみたらポジションが悪いのでモジモジするような、なんか収まりが悪いといった個人的な内容ですしね。

バグか不具合かはラベルチームが行うとして、動かないといったクリティカルな問題以外で、もっと Qithub らしい表現ないですかね。

「不都合な真実を発見しました」「気持ち悪いものを見つけました」

うーん、長いなぁ、虫（Bug）かわからんけど気持ち悪いもので、、、「G」？

合わせて「G/B」とか。ローカル言語すぎるか。

とりあえず「問題報告」に修正してみました。

**Comment by KEINOS** [comment]
「問題」すらも重いので「問題報告」→「報告」に変えました。

**Comment by hidao80** [comment]
正確な定義は難しいですが、個人的には以下のようなニュアンスで呼びわけをしています。

* 完全に想定外、的外れの挙動をする実装：バグ
* 要件定義に近いが一致していない実装：不具合

…言葉は組織を表しますねぇ。

**Comment by KEINOS** [comment]
メキシコでは学校で「意図しない動作をしたときの原因」を総称してバグと習っていたので日本に来てから違和感を持ったのは、そこかもしれないですね。不具合というニュアンス的（はっきりと定義されていない）条件が増えたりとか。

当時は、それが日本のサービスの品質にもつながっているんだなと思っていましたが、考えてみれば（追加で）お金が出るか出ないかの重要なキーワードなんですよね。
何でも無償で修正させられていたのは、そこの使い分けをきちんとせずに何でも「バグ」として受け取ってたからなんだと認識しました。

**Comment by hidao80** [comment]
👍😄
