### ISSUE TITLE
プロセス：「新着Qiita記事」の取りまとめトゥートのタグの順番（ソート）

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/scripts#70]
## 提案

取りまとめトゥートのタグ一覧をACB順にしてはどうか。
https://qiitadon.com/@qithub/99086657870456497

## 自分の案

現在は登録された順なのですが、ABC順の方が見やすいと感じたので、[タグ一覧のループ処理](https://github.com/Qithub-BOT/scripts/blob/master/includes/proc/toot-daily-qiita-items.php.inc#L133)の直前に配列をソートしてどうか。

## 補足

上記は開発側や初見の人に綺麗見えるといった見栄え目線で、今後ユーザーが「タグ検索→取りまとめトゥートがヒット→トゥートを開いて該当記事を探す」という順番があることを考えると、慣れた人には時系列のままの方がいいのかもしれない。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（進捗・決定  2017/12/12 現在）

- ソートすることに決定
    - 取りまとめトゥート内のタグは半角英数カタカナ処理済みのため、昇順でソートすることに
    - <del>issue #62 と一緒に[ブランチ](https://github.com/Qithub-BOT/scripts/tree/fix%2362-over_500chars_not_reporting-20171207)してます。ヽ(*´∀`)/</del> → PR #76 で対応済み

**Comment by hidao80** [comment]
ABC 順に 👍

杞憂だとは思いますが、unicode 順とした場合、「A → Ａ → あ」（2番目は全角のA）になるんでしたっけ？

半角アルファベットと全角アルファベットの並びが気になります。

P.S.
unicode 調べてみました。（出典：<http://www.asahi-net.or.jp/~ax2s-kmtn/ref/unicode/index_u.html>）  
コードでソートすると、**「A → あ → ア → Ａ → ｱ」**となるようです。  
美しいソートが面倒くさいようなら、新着順でもいいかも…

と、いうわけで、

1. Qiita のタグが全角英文字、半角カナのどちらか一方でも対応していれば、**新着順**
1. 〃 の両方に対応していなければ、**ABC 順**

で、どうでしょうか？

**Comment by KEINOS** [comment]
軽くQiitaのタグを検証してみたのですが、基本的に保存時に**半角カナは全角に変換**され**全角英数字は半角に変換されます**。

**問題は混在していた場合**で、全角カナ＋半角英数字、全角英字＋半角数字などといった場合には、変換されないようです。

https://qiita.com/KEINOS_BOT/items/6ed50b45639e28911618
☝️ 検証途中で力つきました。先に組み合わせ表を作ってから調べればよかった。

ただ、そもそも Qiita のタグと Mastodon のタグでは（Mastoでは`-`が使えないなど）禁則文字や条件が違うので、 Qithub の仕様で以下のように統一させてソートをかけちゃってもいいかなと思いました。

- 英数字は全て半角
- 半角カタカナは全角に変換

[現時点でタグにかけている変換処理](https://github.com/Qithub-BOT/scripts/blob/master/includes/functions.php.inc#L698)に、上記の変換を加えれば工数少ないかな、と。

**Comment by KEINOS** [comment]
ってか、[すでにかけてた](https://github.com/Qithub-BOT/scripts/blob/master/includes/functions.php.inc#L710)、、、。(´・ω・｀)
ってことはソートすればOKってことですかね。

**Comment by hidao80** [comment]
検証ありがとうござい💪

ソートでいきましょう。😊
