### ISSUE TITLE
プロセス：「新着Qiita記事」のユーザごとの Qiita 記事リスト構想

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/scripts#71]
## 提案

開いた新着Qiita記事の同じユーザーの記事一覧が見れるようにしたい

## 自分の案①

Qithub の前身の [tootbot 時代にやりとりされた過去のトゥート](https://qiitadon.com/@hidao/449643)を見ていたら、

> `＃ユーザID` のハッシュタグをクリックすれば、そのユーザーの記事一覧が見れるようにした

ことを失念していました。同じ実装です。

ユーザー名の変数に加える「＠」の変わりに「#」を加えた変数（例：`#KEINOS`）を新たに設けるだけなので、工数的には多くないと思いますが、実装前の過去の記事がヒットしないという問題があります。

## 自分の案②

BOTで指定したユーザーの記事一覧を返す。

> ＠qithub:get-items-qiita <ユーザーID> all
> ＠qithub:get-items-qiita <ユーザーID> 0-3

過去の記事は網羅できますが、一手間かかる。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（結論 2017/12/12 現在）

- 提案①を採用

    > トゥート内のタグにユーザーアカウントタグを新規に追加する
    - → PR #76 で対応済み

**Comment by hidao80** [comment]
案① に👍

案②には、次のようなデメリットが考えられます。

a. 新規のプラグイン実装が必要です（高コスト）。
b. トゥートからのプラグイン実行機能が BOT に実装されるのを待つ必要があります。（即効性がない）
c. b. を回避すると、URL パラメータを解釈して動作する実装が必要で、将来的に不要になると考えられます（冗長）。

ここからさらに 2 つの案を提案します。

## 案A：ユーザアカウントタグ化前の投稿を無視する

メリット：おそらく最も早く実施でき、実装も簡単な施策だと思われます。  
デメリット：案①の通り、実装前の投稿をピックアップできません。

## 案B：案①実装後、機を見て案②を実装する。

メリット：当初の目的が達成できます。
デメリット：当該ユーザの Qiita 記事を探す方法が 2 重化します。

--------

ユーザ名タグで検索できると Mastodon ネイティブな感じがして非常に良いと感じます。😊

正直、案②まで必要かな？ と思いますが、** 「Qithub は Qiita と Qiitadon を網羅する」 **というビジョンがあるのなら避けては通れないと考えます。🤔

**Comment by KEINOS** [comment]
では 案①の案Aにしましょう！

確かに、案②のプラグインは、**やってみたい Qithub コマンド（トゥートからのプラグイン実行機能）の実装に近いもの**なので、同じ実装したいコマンドであれば、個人的な優先度としては「[フォロワーがブーストしたトゥートを保存して検索対象にする](https://github.com/Qithub-BOT/items/issues/14#issuecomment-340248589)」方が良いと思いますし。

いずれにしても、トゥートからのプラグイン実行機能ありきなので、これが出来てから欲しくなったら別 issue を立てるなりにして、今回は「トゥート内のタグにユーザーアカウントタグを新規に追加する」で 👌 ？

**Comment by hidao80** [comment]
👌 👍
