### ISSUE TITLE
プロセス：「新着Qiita記事」の取りまとめトゥートのタグ分割文字の追加

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/scripts#72]
## 相談

タグに「全角コンマ」がある場合は分割させたい

> 例：#ダブルクォーテーション、シングルクォーテーション
>  https://qiitadon.com/@qithub/99130516683817004

## 自分の案

各新着記事のトゥート時に、すでに[「,（半角カンマ）」を含むタグを分割処理している位置](https://github.com/Qithub-BOT/scripts/blob/master/includes/proc/toot-daily-qiita-items.php.inc#L322)より前に「全角→半角」置換処理を追加すれば、あとは従来通りの処理にまかせられるかと。

Qithub 側だけのタグのクオリティをあげても記事へのアクセス数向上に貢献できるか疑問ですが、何れにしてもプライオリティは低めだと思います。

## TL;DR（進捗 2017/12/07 現在）

- タグ区切りを意図しないコンマ（カンマ）の利用も考えられるので経過観察することに。
    - 進捗：他の issue がクリアされるまで様子を見て、対応するかクローズするか決める

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

**Comment by hidao80** [comment]
# _リポジトリ内コードの任意行にリンクを張っているのがすげえ。_ 🤩

閑話休題。

総論👍 ですが、**記事の著者が意図的にタグを Atomic にしていない場合、副作用になる**のでは？ と危惧しています。

>例)
>タグ：`PHP`, `Mastodon`, `RaspberryPi`,`サーバ`,`運用、管理`

…適切な例が挙げられなくて悔しいと思ってる。😢

**Comment by KEINOS** [comment]
この前、例の「[なくてもいいけど、ぶっちゃけやりたい機能](https://github.com/Qithub-BOT/items/issues/14)」で、同ページ内の各コメントに目次からリンクを貼った時に、「ソースにもできるんじゃね？」と思って（ソースの行番号のリンクを）貼ったらできました。 😄 

さて、表題の件ですが、今回の件は恐らく類似のタグを**あえて「カンマ」つながり**で書いて、Qiita の最大タグ数５つの制限回避を目的としたものだと思うのですが、確かにそれ以外にもあるかもしれないですね。「#なんだ、と」みたいな。

他の issue がクリアされるまで様子を見て、対応するかクローズするか決めましょう。

**Comment by hidao80** [comment]
👍

**Comment by KEINOS** [comment]
あれ以来、「、」区切りの記事はないようですし、一旦この issue はクローズしませんか？
👌 ならクローズお願いし 💪
