### ISSUE TITLE
'system'と'plugins'：Qithub 標準関数の作成とディレクトリの統合

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/scripts#77]
## 提案

1. Qithub API のデータ送受信専用の標準的な関数を用意したい
2. `system` と `plugins` を統合したい（2017/12/21 追記→[参照](#issuecomment-353116476)）

### 標準関数の作成理由

1. `plugins` `system` の各々に毎回同じ API の入出力を実装しないといけない
2. API の入出力の仕様自体は `plugin` 本体の動作とは別の目的である
3. プラグイン本体の動作に注力したい
4. コピペと修正が毎回面倒

まぁ、４が一番の理由なのですが、コピペしたとしても API の入出力部分を修正・改善（リファクタリング）したら、他の箇所も変えないとならず、共通動作の部分がプラグインによってまちまちになっており、**可読性が損なわれてる**という現状があります。

### プラグインのテンプレート例
下記の`get_api_input_as_array()`と`print_output_as_api()`が Qithub標準関数の例です。
```main.php
<?php
// Qithub標準関数の読み込み（PHP.iniでパスを通しておく）
include_once('qithub-api.php.inc');

// Qithub API 経由でのデータの受け取り（QithubAPIフォーマットから配列へ変換）
$args = get_api_input_as_array();

// 受け取ったデータで各々の処理
/* do whatever you want */
$result = print_r($args, true); // sample

// 処理結果の準備
$status   = 'OK'; // 処理結果のステータス（'OK' / 'NG'）
$contents = $result; // 処理結果の内容（配列でも可）

// 処理結果の出力
print_output_as_api( $status, $contents ); // QithubAPI準拠のフォーマットで出力

```

`plugins`や`system`の「自身のディレクトリ外へのアクセス」に触れるかもしれないのですが、API の入出力のことを考えなくて済むだけでも、プラグインは開発しやすいのではないかと思います。

Qithub API の仕様自体はシンプルとは言え、何かを使うのにインストールでつまずいてやる気を削がれるのと同じようなものをプラグインで感じます。

理想で言えば、（`samples/plugins/`に設置した）テンプレートをコピーするだけで標準入力と標準出力が使える状態のものを用意して、そこから**内容だけに注力する**ことができる環境であればいいな、と。

さらなる理想を言えば、Qithub ではテスト環境だけ用意して、 paiza.IO で開発してテストをパスしたものがマージされるような環境であれば、もっと良いのですが。

## 補足

標準関数の準備はPHPだけなら問題ないのですが、他の言語のぶんも用意しないといけなくなりますが、ここは勉強をせねば。

----------------

- [x] 過去の Issues も検索しましたが該当するものはありませんでした。

----------------

## TL;DR（結論 2017/12/21 現在）

- 汎用関数の作成に関してはペンディングとし、代わりに[スニペットをまとめたファイルを設置する](#issuecomment-351946006)
    - PR #85 で[設置済み](https://github.com/Qithub-BOT/scripts/blob/master/system/Qithub-wrapper-snippets.md)
- `system` と `plugins` を [`plugins` に統合する](#issuecomment-353185164)ことに
    1. `plugins/<your-plugin>/` の同階層に `info.json` ファイルを設置（ issue #84 を[参照](https://github.com/Qithub-BOT/scripts/issues/84#issuecomment-352418799)）
    2. `plugin`がアクセストークンを必要とする場合は `info.json` に記載すること（仕様は別途制定する）

**Comment by hidao80** [comment]
むむ。私が誤解しているようなので確認させてください。

>テンプレートをコピーするだけで標準入力と標準出力が使える状態のものを用意して

1. ここで言う「標準入力/出力」とは、Qiita API の GET/POST の事ですか？ それともターミナル（プラグイン）への入出力ですか？
1. 「テンプレートをコピー」とは、「ソースコードのコピペ」の事を意味していますか？上記コードの書かれたファイルのことですか？

これらによっては意見が 180 度変わりそうなのです。

**Comment by KEINOS** [comment]
そうか。Qithub を外部からアクセスするのも API だし、Qithub 内で本体とプラグイン間でのやりとりも API だから、これではどれを指すかわかりづらいですね。失礼いたしました。

> >テンプレートをコピーするだけで標準入力と標準出力が使える状態のものを用意して
> 
> 1. ここで言う「標準入力/出力」とは、Qiita API の GET/POST の事ですか？ それともターミナル（プラグイン）への入出力ですか？

ターミナル、つまりプラグインから見て本体から受け取る入力の「標準入力」と、本体がプラグインから受け取る「標準出力」を指しています。

> 2. 「テンプレートをコピー」とは、「ソースコードのコピペ」の事を意味していますか？上記コードの書かれたファイル「テンプレート」と呼び、ファイルをコピーするということですか？

「ソースコードのコピペ」です。テンプレートでなく「プラグインのサンプルコード」と言った方がいいかもしれませんね。

ご意見お待ちしてい 💪

**Comment by hidao80** [comment]
私は重複しない固有名詞があった方が理解が早いので、以下定義。

- Qiita-API：Qiita の機能にアクセスする API。URL にオプションをつけて使用する。[要出典]
- Qithub-API：Qithub の機能にアクセスする API。Qithub を実行しているサーバ上で、標準入出力を介して使用する。
- Qiita-API ラッパー関数：任意のプログラミング言語で簡単に当該 Qiita-API を動作させる関数。
- スニペット：本 issue での「テンプレート」に対応する。よく使うコードのコピペ元。

## 案A

### 骨子

- Qiita-API ラッパー関数（Qithub-API であってもなくても可）を定義するよ
- Qiita-API ラッパー関数はコピペで使えるようにするよ
- Qiita-API ラッパー関数群（Qiita-API 数 × プラグイン実行可能言語数）をまとめた Markdown ファイルを作りませんか?
- コピペ推奨なのが DRY 原則違反だけど、KISS なので許すよ。

### TL;DR

結論から言うと、`plugins/Qiita-API-wrapper-snippet.md` を作って、その中に**全ての Qiita-API ラッパー関数** をスニペットとして記述しておきませんか、と言うことです。

------

コピペはコピペ元コード（=スニペット）の世代違いによるエンバグ問題をはらんでいるうえ、同じコードを複数箇所に分散してしまうソリューションです。\
Qiita-API ラッパー関数を改善したばあい、**必要な全てのコピー箇所を修正しなければならず**、将来的にコスト高になってしまうところは留意しておくべきでしょう。

ですが、

- 初期投資が少ない（=早く、簡単にできる）
- Qiita-API ラッパー関数をブラックボックス化しない
- **Qiita-API ラッパー関数がない言語でも、気合いがあればプラグインが作れる（重要）**

将来的にはライブラリ（ファイル）にして `import` とか `include` キーワードかなんかで当該プログラミング言語の Qiita-API ラッパー関数全てをごっそり引っ張れるようにしたいですが、**たちまちはコピペでよい**と思います。**我々が真にやりたいのはフレームワークづくりではなく、「動いて楽しいもの」のはずです。**

**Comment by KEINOS** [comment]
> plugins/Qiita-API-wrapper-snippet.md を作って、その中に**全ての Qiita-API ラッパー** をスニペットとして記述

なるほど。まずはそこからスタートしましょうか！

issue #66 の「Qiitaコラボ記事を GitHub から Qiita へデプロイする」 PR をあげる際に、
 `plugins/README.md` のアップデートと、スニペットも一緒にあげるので、そこでこの issue のクローズについてディスカッションを続けたいと思います。[[ブランチはこちら](https://github.com/Qithub-BOT/scripts/tree/%2366-process-add-deploy_item_to_qiita-20171207)]

なお、API やラッパーの用語に関しては、すり合わせが必要そうなので、別途 issue を立てますね。

**Comment by KEINOS** [comment]
### 提案

共通関数の作成（コピペの更新が面倒）の件で、スニペットを書いていて思ったのですが、**`system` と `plugins` をシンプルに１つにまとめられる**気がします。（ #78 の[`process` を `procedure` にするのとは別の話](https://github.com/Qithub-BOT/scripts/issues/78#issuecomment-353069109)）

`system` と `plugins` の唯一の**違いはスクリプトがアクセストークンを受け取れるか否かだけ**で、I/O の仕組みや呼び出しに関してはまったく同じ動作をしており、両者とも WEB 経由でダイレクトにアクセスできないため、セキュリティのリスクは同等と感じます。

そこで、 issue  #84 で[言及されている](https://github.com/Qithub-BOT/scripts/issues/84#issuecomment-352418799)「プラグインの情報を記載した JSON ファイルを同階層に置くことで、プラグインのバージョン、ヘルプ、デフォルトのプログラム言語に対応する」仕様に、「アクセストークンを必要とする場合は、その旨を記述しておく」ことで、`systems`と`plugins`を同じ`plugins` ディレクトリに設置でき、かつ作るたびに index.php を編集しなくて済むようになると思いました。

議論の余地があれば issue を立てたいと思うのですが、いかがでしょう？

**Comment by hidao80** [comment]
Qithub エンコード・データに `"sudo":"true"` のような項目追加に 👍

これならアクセストークンも通信に乗らず、**安全かつ誰でも Qiita に干渉できるプラグインが作れ**ますね🤩

> index.php を編集しなくて済む

これはとても良い副作用ですね！👍 core 部分がマイクロ化して行ってとても KISS でいい感じ。

この件はこれで全面的に👌👍です。

issue は不要だと思います。リファレンス用に立てて、結論を TL;DL にまとめるのはありだと思います。

**Comment by KEINOS** [comment]
> この件はこれで全面的に👌👍です。

👍 

> issue は不要だと思います。リファレンス用に立てて、結論を TL;DL にまとめるのはありだと思います。

👍 👉 TL;DR 済 & Close

`plugins/` の各プラグイン・ディレクトリ下に置く `info.json` の記述内容に関しては、モデルケースを作成後、別途制定したいと思います。
